########## SECTION 1 - GENERAL SETTINGS ##########
########## Will probably never change
url: "https://helptest.theobald-software.com"
baseurl: ""

# Name of website
title: Theobald Online Help
# Short description of site
description: Theobald's Online Help Portal contains all documentation about our products

# For variables in the head such as for twitter cards
author:
  name: Theobald Software
  twitter: TheobaldSoftw

# Maximum depth for breadcrumb. Do not change.
breadcrumb_list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

algolia:
  application_id: '4C27F1P1UC'
  index_name: theobald-software-online-help

########## SECTION 2 - HEADER CONTENT ##########
########## These are configurable here rather than in the html pages and include files
########## Languages can easily be added this way as well.
##########  see the readme file for more information regarding that,
##########  requires more than just adding a language here.
language:
  en:
    navbar-links:
      - title: "Go to Knowledgebase"
        url: "https://my.theobald-software.com/index.php?/Knowledgebase/List"
      - title: "Return to Theobald Software"
        url: "https://theobald-software.com/en/"
    homepage: Homepage
    language: Language
  de:
    navbar-links:
      - title: "Gehe zum Knowledgebase"
        url: "https://my.theobald-software.com/index.php?/Knowledgebase/List"
      - title: "Zurück zum Theobald Software"
        url: "https://theobald-software.com/de/"
    homepage: Startseite
    language: Sprache

########## SECTION 3 - COLLECTION CONFIGURATIONS ##########
########## Languages can easily be added this way.
##########  see the readme file for more information regarding that,
##########  requires more than just adding a language here.
collections_dir: content
collections:
  en:
    output: true
    name: 'English'
    language_label: 'gb'
  de:
    output: true
    name: 'Deutsch'
    language_label: 'de'
########## SECTION 4 - OTHER SETTINGS ##########
########## Be careful with changes to these settings, as it could break things.
timezone: "Europe/Berlin"
markdown: kramdown
highlighter: rouge
plugins:
- jekyll-sitemap
- jekyll-redirect-from
# sass (styling)
sass:
  sass_dir: css/scss
  style: compressed
# Default YAML values
defaults:
  - scope:
      path: "" # all files
    values:
      layout: "page"
# Exclude
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - Vagrantfile
  - .idea/workspace.xml
  - vendor
# prose.io - easy editing
# TODO: needs more configuring to work properly
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "image"
        field:
          element: "text"
          label: "Image"
          help: "Add a thumbnail image to your post."
          placeholder: "Thumbnail"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

########## SECTION 5 - TRACK SETTINGS ##########
# GA gatg.js ID
#gtag: ""
# GA ID
#google_analytics: ""
# GTM ID
#gtm: ""